// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASK_jmuRZZ4vAj9dP8SHnej8R9n3__l-s',
    appId: '1:831891904212:web:c732e136b8f21cc9ff0d41',
    messagingSenderId: '831891904212',
    projectId: 'feeddev-725e4',
    authDomain: 'feeddev-725e4.firebaseapp.com',
    storageBucket: 'feeddev-725e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiC5hw6NYwsccaFLzWmqnfHETDgf1Gj78',
    appId: '1:831891904212:android:e8c6b262873058cfff0d41',
    messagingSenderId: '831891904212',
    projectId: 'feeddev-725e4',
    storageBucket: 'feeddev-725e4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDp3NJkFIs73yZMJJzl28V8DGNCNIev14',
    appId: '1:831891904212:ios:3a9ffcbd431460a8ff0d41',
    messagingSenderId: '831891904212',
    projectId: 'feeddev-725e4',
    storageBucket: 'feeddev-725e4.firebasestorage.app',
    iosBundleId: 'com.example.ss20',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDp3NJkFIs73yZMJJzl28V8DGNCNIev14',
    appId: '1:831891904212:ios:3a9ffcbd431460a8ff0d41',
    messagingSenderId: '831891904212',
    projectId: 'feeddev-725e4',
    storageBucket: 'feeddev-725e4.firebasestorage.app',
    iosBundleId: 'com.example.ss20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASK_jmuRZZ4vAj9dP8SHnej8R9n3__l-s',
    appId: '1:831891904212:web:c9fe10f6b8386d47ff0d41',
    messagingSenderId: '831891904212',
    projectId: 'feeddev-725e4',
    authDomain: 'feeddev-725e4.firebaseapp.com',
    storageBucket: 'feeddev-725e4.firebasestorage.app',
  );
}
